# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slaude < Formula
  desc "Claude Code ↔ Slack bridge"
  homepage "https://github.com/sttts/slagent"
  version "2026.3.10-alpha.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.10-alpha.18/slaude_darwin_amd64.tar.gz"
      sha256 "b3d01d69cd22f9e62bcc2536bd94bded95ffa684d6a5cbcdd8c7678f659694f3"

      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.10-alpha.18/slaude_darwin_arm64.tar.gz"
      sha256 "6dd77ed8b5c70e5bcba172a3369ffbfb523300ec3b9309cab053c070cc959b5a"

      define_method(:install) do
        bin.install "slaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.10-alpha.18/slaude_linux_amd64.tar.gz"
      sha256 "bd866d87067009f2e6fc9eeb3d41d53730cca00e04be0a4998784f83ca292601"
      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.10-alpha.18/slaude_linux_arm64.tar.gz"
      sha256 "680c545cece9a534b1ffdd1e3e08423b7d7030889a2211f931c2d0a619587e85"
      define_method(:install) do
        bin.install "slaude"
      end
    end
  end
end
