# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slaude < Formula
  desc "Claude Code ↔ Slack bridge"
  homepage "https://github.com/sttts/slagent"
  version "2026.3.9-alpha.12"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.12/slaude_darwin_amd64.tar.gz"
      sha256 "3bba3dea7d23283771b747991f2ddc1d2bcd885c0ba9bcc99c018e136e369f63"

      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.12/slaude_darwin_arm64.tar.gz"
      sha256 "84d274c884ae8d3a6951c02706cb8efbf1266385580ef574111aceca77b8e98e"

      define_method(:install) do
        bin.install "slaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.12/slaude_linux_amd64.tar.gz"
      sha256 "a6ce466fa5e04189864343a44bb5282b2da6161256c3e38c56b4f7db525d85d5"
      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.9-alpha.12/slaude_linux_arm64.tar.gz"
      sha256 "5b4a8f2c108c68b2e7a25d4cecd34a2582ec72a98b9e9f2e57cc298379848beb"
      define_method(:install) do
        bin.install "slaude"
      end
    end
  end
end
