# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slaude < Formula
  desc "Claude Code ↔ Slack bridge"
  homepage "https://github.com/sttts/slagent"
  version "2026.3.19-alpha.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.19-alpha.0/slaude_darwin_amd64.tar.gz"
      sha256 "e0c0bdf233d46d57c70650d06b67fbc0e32ec6352b9a65463f5eeaee63897f40"

      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.19-alpha.0/slaude_darwin_arm64.tar.gz"
      sha256 "9f5db4cc8fabd6e2e9be0007ce12215bf8e99104762e6c1b2c8db758e1178b28"

      define_method(:install) do
        bin.install "slaude"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.19-alpha.0/slaude_linux_amd64.tar.gz"
      sha256 "17b070af861569bd44123058860139f1c4932a6294c35c31648c2b3784828061"
      define_method(:install) do
        bin.install "slaude"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sttts/slagent/releases/download/v2026.3.19-alpha.0/slaude_linux_arm64.tar.gz"
      sha256 "563ffc7f73a47a18a3f302808da3afaaa2baeab69744ded7803bc598de8b73f6"
      define_method(:install) do
        bin.install "slaude"
      end
    end
  end
end
